#!/bin/bash

### Helper functions
function server() {
if [[ -z $1 ]]; then
  PORT=8000
else
  PORT="$1"
fi

chromium-browser  "http://localhost:$PORT" &
python -m SimpleHTTPServer $PORT
}

# Compute gzip size of file
function gsize() {
if [[ -z $1 ]]; then
  exit 1
fi

gzip -c "$1" | wc -c
}

# A bash function to display a growl notification using iTerm's magic
# escape sequence. This version will work under screen.
growl() {
  local msg="\\e]9;\n\n${*}\\007"
  case $TERM in
    screen*)
      echo -ne '\eP'${msg}'\e\\' ;;
    *)
      echo -ne ${msg} ;;
  esac
  return
}

# Fixes that fucking annoying coreaudio breakdown
fuckingairplay() {
  sudo kill `ps -ax | grep 'coreaudiod' | grep 'sbin' |awk '{print $1}'`
}

fancy-ctrl-z () {
  if [[ $#BUFFER -eq 0 ]]; then
    fg
    zle redisplay
  else
    zle push-input
    zle clear-screen
  fi
}

zle -N fancy-ctrl-z
bindkey '^Z' fancy-ctrl-z
